"""
scripts/sync_params.py

PHASE 2, STEP 4 — KEEP params.yaml IN SYNC WITH THE ACTIVE HYDRA CONFIG

WHY THIS SCRIPT EXISTS:
  params.yaml (Phase 2 Step 3) and the Hydra config hierarchy (Step 4) are
  two different systems with two different jobs:
    - Hydra configs: the REAL source of truth, what train.py actually loads
      and runs with. Supports composition, overrides, multirun sweeps.
    - params.yaml: a FLAT file DVC reads to decide whether a pipeline stage
      is stale. DVC's params: mechanism cannot understand Hydra's defaults:
      composition — it just reads one resolved flat YAML file and hashes it.

  Hand-maintaining both in sync (manually copying values whenever you change
  a Hydra config) is exactly the kind of process that silently drifts —
  someone changes training.lr in configs/training/base.yaml, forgets to
  also update params.yaml, and DVC's staleness tracking becomes a lie: it
  thinks the train stage is still valid when the REAL config has actually
  changed. This script eliminates the manual step entirely by deriving
  params.yaml FROM the resolved Hydra config, programmatically, every time.

WHEN TO RUN THIS:
  Run it once before `dvc repro` whenever you've changed any Hydra config
  file OR are about to run a different experiment override. The natural
  place this belongs is as a pre-step in your training script invocation,
  or as a make-style command — for now, run it manually:

      python scripts/sync_params.py
      python scripts/sync_params.py schedule=linear     # same override syntax as train.py

  WHY NOT AUTOMATE THIS INSIDE train.py ITSELF: params.yaml needs to exist
  and be correct BEFORE dvc repro decides whether to even invoke train.py —
  the sync has to happen as its own preceding step, not nested inside the
  stage it's meant to gate.
"""

import sys
from pathlib import Path

import hydra
import yaml
from omegaconf import DictConfig, OmegaConf


# The exact set of dotted paths our dvc.yaml stages reference via `params:`.
# WHY hardcoded here rather than parsing dvc.yaml automatically: dvc.yaml's
# params: lists are deliberately curated (only the values that should
# actually trigger staleness — see Step 3's dvc.yaml comments on why e.g.
# num_workers is NOT a staleness trigger but training.lr IS). Auto-deriving
# this list from dvc.yaml would silently sync FZ every value Hydra knows
# about, including ones we deliberately excluded from staleness tracking.
DVC_TRACKED_PARAM_PATHS = [
    "seed",
    "data.normalize_mean",
    "data.normalize_std",
    "model.base_channels",
    "model.channel_mult",
    "model.num_res_blocks",
    "model.attention_resolutions",
    "model.cfg_dropout",
    "schedule.T",
    "schedule.type",
    "training.lr",
    "training.batch_size",
    "training.num_epochs",
    "training.ema_decay",
    "evaluation.num_samples_fid",
    "evaluation.ddim_steps_list",
    "evaluation.cfg_guidance_scale",
    "quantization.methods",
    "quantization.calibration_samples",
]


def get_nested(cfg: DictConfig, dotted_path: str):
    """Walk a dotted path like 'model.base_channels' through cfg.experiment.*"""
    keys = dotted_path.split(".")
    cur = cfg.experiment
    for k in keys:
        cur = cur[k]
    return OmegaConf.to_container(cur) if hasattr(cur, "__iter__") and not isinstance(cur, str) else cur


def set_nested(d: dict, dotted_path: str, value) -> None:
    """Set a value into a nested dict, creating intermediate dicts as needed."""
    keys = dotted_path.split(".")
    cur = d
    for k in keys[:-1]:
        cur = cur.setdefault(k, {})
    cur[keys[-1]] = value


@hydra.main(version_base=None, config_path="../configs", config_name="config")
def main(cfg: DictConfig) -> None:
    params_dict: dict = {}

    missing_paths = []
    for path in DVC_TRACKED_PARAM_PATHS:
        try:
            value = get_nested(cfg, path)
            set_nested(params_dict, path, value)
        except Exception:
            missing_paths.append(path)

    if missing_paths:
        print("WARNING — these DVC-tracked param paths were not found in the "
              "resolved Hydra config (params.yaml will be missing them):")
        for p in missing_paths:
            print(f"    {p}")
        print("This usually means a Hydra config file is missing a field that "
              "dvc.yaml expects, or evaluation/quantization config groups "
              "haven't been added to configs/experiment/baseline.yaml's "
              "defaults: list yet (expected until Phase 4/5 add those groups).")

    output_path = Path("params.yaml")
    with open(output_path, "w") as f:
        f.write("# AUTO-GENERATED by scripts/sync_params.py — DO NOT HAND-EDIT.\n")
        f.write("# Source of truth is the Hydra config hierarchy in configs/.\n")
        f.write("# Re-run sync_params.py after changing any Hydra config file.\n\n")
        yaml.dump(params_dict, f, default_flow_style=False, sort_keys=False)

    print(f"Synced params.yaml from resolved Hydra config "
          f"(experiment={cfg.experiment.experiment_name})")
    print(f"Wrote {len(DVC_TRACKED_PARAM_PATHS) - len(missing_paths)} / "
          f"{len(DVC_TRACKED_PARAM_PATHS)} tracked param paths")


if __name__ == "__main__":
    main()